export const TEST_CHEOUT = 'TEST_CHEOUT'
export const SET_HAS_SHIPPING = 'SET_HAS_SHIPPING'
export const SET_BILLING_CHANGES = 'SET_CHANGES'
export const SET_LOCATIONS = 'SET_LOCATIONS'
export const SET_DEFAULT_ADDRESS = 'SET_DEFAULT_ADDRESS'
export const SET_BILLING_CITY = 'SET_BILLING_CITY'
export const SET_BILLING_AREA = 'SET_BILLING_AREA'
export const SET_BILLING_ADDRESS = 'SET_BILLING_ADDRESS'
export const SET_BILLING_DIVISION_ID = 'SET_BILLING_DIVISION_ID'

export const SET_SHIPPING_CITY = 'SET_SHIPPING_CITY'
export const SET_SHIPPING_AREA = 'SET_SHIPPING_AREA'
export const SET_SHIPPING_ADDRESS = 'SET_SHIPPING_ADDRESS'
export const SET_FORM_INITIAL_VLAUE_NULL = 'SET_FORM_INITIAL_VLAUE_NULL'

export const SET_OFFER_DISCOUNT = 'SET_OFFER_DISCOUNT'
export const SET_COUPON = 'SET_COUPON'
export const SET_CREDIT = 'SET_CREDIT'


export const SET_SHIPPING_CHARGE = 'SET_SHIPPING_CHARGE'