export const SET_USER_INFO = 'SET_USER_INFO'
export const SET_AUTH_LOADING = 'SET_AUTH_LOADING'
export const USER_REGISTRATION = 'USER_REGISTRATION'
export const LOG_OUT = 'LOG_OUT'
export const MOBILE_USER_ACCOUNT = 'MOBILE_USER_ACCOUNT'

export const SET_RECENT_SEARCH = 'SET_RECENT_SEARCH'
export const DELETE_RECENT_SEARCH = 'DLETE_RECENT_SEARCH'

export const SET_RECENT_VIEW = 'SET_RECENT_VIEW'

export const CHANGE_WISH_LIST = 'CHANGE_WISH_LIST'